name = "Min Stock Notifier"
client_id = "replace_with_your_client_id"
application_url = "https://productalert.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [
  "https://productalert.vercel.app/auth/callback",
  "https://productalert.vercel.app/auth/shopify/callback",
  "https://productalert.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "inventory_levels/update" ]
uri = "/webhooks/inventory-levels-update"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhooks/customers/data-request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhooks/shop/redact"

[pos]
embedded = false
