name = "Min Stock Notifier"
client_id = "b9c12006a26e2d23e68a4b7852490171"
application_url = "https://productalert.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [
  "https://productalert.vercel.app/auth/callback",
  "https://productalert.vercel.app/auth/shopify/callback",
  "https://productalert.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "inventory_levels/update" ]
uri = "/webhooks/inventory-levels-update"

[webhooks.privacy_compliance]
customer_data_request_url = "https://productalert.vercel.app/webhooks/customers/data-request"
customer_deletion_url = "https://productalert.vercel.app/webhooks/customers/redact"
shop_deletion_url = "https://productalert.vercel.app/webhooks/shop/redact"

[pos]
embedded = false
